#! /usr/bin/env perl
$latex  = 'platex -kanji=utf8 -src-specials -interaction=nonstopmode';
$bibtex = 'pbibtex -kanji=utf8';
$dvips  = 'dvipsk';
$dvipdf  = 'dvipdfmx %O -o %D %S';
$makeindex  = 'mendex -U -r -c -s dot.ist';
$dvi_previewer ='xdvi';
$pdf_previewer = 'okular %O %S';
$pdf_mode = 3;
$pdf_update_method = 0;
